import { useEffect, useState } from "react";
import { ordersApi, paymentsApi } from "../api/resources";
import { apiError } from "../api/client";
import { Empty, ErrorMessage, Loading, Status, date, patientName } from "../components/Common";
export default function Payments() {
  const [payments, setPayments] = useState([]), [orders, setOrders] = useState([]), [form, setForm] = useState({ orderId: "", amount: "", status: "UNPAID", paidAt: "", notes: "" }), [error, setError] = useState(""), [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); Promise.all([paymentsApi.list({ page: 1, limit: 100 }), ordersApi.list({ page: 1, limit: 100 })]).then(([p, o]) => { setPayments(p.data.payments); setOrders(o.data.orders); }).catch((e) => setError(apiError(e))).finally(() => setLoading(false)); }; useEffect(load, []);
  const submit = async (e) => { e.preventDefault(); setError(""); try { await paymentsApi.create({ orderId: form.orderId, amount: form.amount, status: form.status, ...(form.paidAt ? { paidAt: form.paidAt } : {}), ...(form.notes.trim() ? { notes: form.notes.trim() } : {}) }); setForm({ orderId: "", amount: "", status: "UNPAID", paidAt: "", notes: "" }); load(); } catch (err) { setError(apiError(err)); } };
  return <><header className="page-header"><div><h1>Payments</h1><p>Record payment entries against a test order.</p></div></header><ErrorMessage error={error} /><form className="panel form-grid" onSubmit={submit}><h2 className="full">Record payment</h2><label className="full">Order<select required value={form.orderId} onChange={(e) => setForm({ ...form, orderId: e.target.value })}><option value="">Choose order</option>{orders.map((order) => <option key={order.id} value={order.id}>{patientName(order.patient)} — {order.orderedTestItems.map((x) => x.testDefinition.name).join(", ")}</option>)}</select></label><label>Amount<input required min="0.01" step="0.01" type="number" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /></label><label>Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option>UNPAID</option><option>PARTIALLY_PAID</option><option>PAID</option><option>REFUNDED</option></select></label><label>Paid date<input type="date" value={form.paidAt} onChange={(e) => setForm({ ...form, paidAt: e.target.value })} /></label><label>Notes<input value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label><div className="full"><button>Save payment</button></div></form>{loading ? <Loading /> : payments.length ? <section className="panel"><table><thead><tr><th>Patient</th><th>Amount</th><th>Status</th><th>Paid on</th><th>Notes</th></tr></thead><tbody>{payments.map((payment) => <tr key={payment.id}><td>{patientName(payment.order.patient)}</td><td>{Number(payment.amount).toFixed(2)}</td><td><Status value={payment.status} /></td><td>{date(payment.paidAt)}</td><td>{payment.notes || "—"}</td></tr>)}</tbody></table></section> : <Empty>No payments recorded.</Empty>}</>;
}
